In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from matplotlib import pyplot as plt

In [3]:
df_prices_fra = pd.read_csv('day_ahead_prices_FRA_2019.csv')
df_load_fra = pd.read_csv('load_FRA_2019.csv')
df_generation_fra = pd.read_csv('generation_per_type_FRA_2019.csv')

dates_fra = df_prices_fra[["MTU (CET)"]].to_numpy().reshape(-1)
prices_fra = df_prices_fra[['Day-ahead Price [EUR/MWh]']].to_numpy().reshape(-1)
load_fra = df_load_fra[['Actual Total Load [MW] - BZN|FR']].to_numpy().reshape(-1)

solar_fra = df_generation_fra[['Solar  - Actual Aggregated [MW]']].to_numpy().reshape(-1)
wind_onshore_fra = df_generation_fra[['Wind Onshore  - Actual Aggregated [MW]']].to_numpy().reshape(-1)
wind_offshore_fra = np.array([0. for i in range(len(wind_onshore_fra))])
nuclear_fra = df_generation_fra[["Nuclear  - Actual Aggregated [MW]"]].to_numpy().reshape(-1)
hydro_water_reservoir_fra = df_generation_fra[["Hydro Water Reservoir  - Actual Aggregated [MW]"]].to_numpy().reshape(-1)
gas_fra = df_generation_fra[["Fossil Gas  - Actual Aggregated [MW]"]].to_numpy().reshape(-1)

france_installed_capacities = {
    "solar": 8.188,
    "wind_onshore": 13.610,
    "wind_offshore": 0.,
    "nuclear": 63.130,
    "gas": 11.952,
}

france_dataframe = pd.DataFrame({
    'date':dates_fra,
    'price':prices_fra,
    'load':load_fra / 1000,
    'nuclear': nuclear_fra / 1000,
    'wind_onshore': wind_onshore_fra / 1000,
    'wind_offshore': wind_offshore_fra / 1000,
    'solar': solar_fra / 1000,
    'gas':gas_fra / 1000,
    'hydro_water_reservoir': hydro_water_reservoir_fra / 1000,
    'solar_load_factor': solar_fra / (france_installed_capacities['solar'] * 1000),
    'wind_onshore_load_factor': wind_onshore_fra / (france_installed_capacities['wind_onshore'] * 1000),
    'wind_offshore_load_factor': wind_offshore_fra,
    'nuclear_load_factor': nuclear_fra / (france_installed_capacities['nuclear'] * 1000),
    'gas_load_factor': gas_fra / (france_installed_capacities['gas'] * 1000),
}, index=[i for i in range(len(dates_fra))])

france_dataframe = france_dataframe[france_dataframe["price"].notna()]

france_dataframe = france_dataframe.dropna()
france_dataframe.to_csv("france.csv", encoding='utf-8', index=False)

france_dataframe

,date,price,load,nuclear,wind_onshore,wind_offshore,solar,gas,hydro_water_reservoir,solar_load_factor,wind_onshore_load_factor,wind_offshore_load_factor,nuclear_load_factor,gas_load_factor
0,01.01.2019 00:00 - 01.01.2019 01:00,51.00,62.176,55.627,1.622,0.0,0.0,2.722,1.054,0.0,0.119177,0.0,0.881150,0.227744
1,01.01.2019 01:00 - 01.01.2019 02:00,46.27,60.301,55.113,1.637,0.0,0.0,2.526,0.740,0.0,0.120279,0.0,0.873008,0.211345
2,01.01.2019 02:00 - 01.01.2019 03:00,39.78,58.540,54.780,1.567,0.0,0.0,2.425,0.463,0.0,0.115136,0.0,0.867733,0.202895
3,01.01.2019 03:00 - 01.01.2019 04:00,27.87,55.144,53.162,1.556,0.0,0.0,2.435,0.145,0.0,0.114328,0.0,0.842104,0.203732
4,01.01.2019 04:00 - 01.01.2019 05:00,23.21,52.978,50.137,1.595,0.0,0.0,2.440,0.097,0.0,0.117193,0.0,0.794187,0.204150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8756,31.12.2019 19:00 - 31.12.2019 20:00,46.00,68.156,49.632,2.220,0.0,0.0,7.605,4.185,0.0,0.163115,0.0,0.786187,0.636295
8757,31.12.2019 20:00 - 31.12.2019 21:00,42.20,64.771,48.940,2.695,0.0,0.0,7.459,3.079,0.0,0.198016,0.0,0.775226,0.624080
8758,31.12.2019 21:00 - 31.12.2019 22:00,39.74,62.259,49.132,2.831,0.0,0.0,7.322,2.493,0.0,0.208009,0.0,0.778267,0.612617
8759,31.12.2019 22:00 - 31.12.2019 23:00,38.88,63.774,48.955,3.031,0.0,0.0,7.260,2.197,0.0,0.222704,0.0,0.775463,0.607430
8760,31.12.2019 23:00 - 01.01.2020 00:00,37.37,65.865,48.992,3.334,0.0,0.0,7.003,2.239,0.0,0.244967,0.0,0.776049,0.585927

In [4]:
df_prices_de = pd.read_csv('day_ahead_prices_DE_LU_2019.csv')
df_load_de = pd.read_csv('load_DE_LU_2019.csv')
df_generation_de = pd.read_csv('generation_per_type_DE_LU_2019.csv')

dates_de = df_prices_de[["MTU (CET)"]].to_numpy().reshape(-1)
prices_de = df_prices_de[['Day-ahead Price [EUR/MWh]']].to_numpy().reshape(-1)
load_de = df_load_de[['Actual Total Load [MW] - BZN|DE-LU']].to_numpy().reshape(-1)

germany_installed_capacities = {
    "solar": 45.435,
    "wind_onshore": 52.946,
    "wind_offshore": 6.393,
    "nuclear": 9.516,
    "gas": 31.745,
    "lignite": 21.205,
    "hard_coal": 25.293,
}

merged_load = []

for i in range(len(prices_de)):
    vals = load_de[4*i : 4*i+4]
    
    if not np.isnan(vals).all():
        merged_load.append(sum(vals) / 4000)
    else:
        merged_load.append(np.nan)
        
merged_load = np.array(merged_load)


columns_names = {
    "solar": "Solar  - Actual Aggregated [MW]",
    "wind_onshore": "Wind Onshore  - Actual Aggregated [MW]",
    "wind_offshore": "Wind Offshore  - Actual Aggregated [MW]",
    "nuclear": "Nuclear  - Actual Aggregated [MW]",
    "gas": "Fossil Gas  - Actual Aggregated [MW]",
    "lignite": "Fossil Brown coal/Lignite  - Actual Aggregated [MW]",
    "hard_coal": "Fossil Hard coal  - Actual Aggregated [MW]"
}

energies_arr = {}

for energy_name, energy_column in columns_names.items():
    arr = df_generation_de[[energy_column]].to_numpy().reshape(-1)

    merged_vals = []
    
    for i in range(len(prices_de)):
        vals = arr[4*i : 4*i+4]

        if not np.isnan(vals).all():
            merged_vals.append(sum(vals) / 4000)
        else:
            merged_vals.append(np.nan)
    
    energies_arr[energy_name] = np.array(merged_vals)
    
    if len(prices_de) != len(merged_vals):
        print("wrong size: " + len(merged_vals))
        
germany_dataframe = pd.DataFrame({
    'date':dates_de,
    'price':prices_de,
    'load':merged_load,
    'nuclear': energies_arr["nuclear"],
    'wind_onshore': energies_arr["wind_onshore"],
    'wind_offshore': energies_arr["wind_offshore"],
    'solar': energies_arr["solar"],
    'gas':energies_arr["gas"],
    'nuclear_load_factor': energies_arr["nuclear"] / germany_installed_capacities["nuclear"],
    'wind_onshore_load_factor': energies_arr["wind_onshore"] / germany_installed_capacities["wind_onshore"],
    'wind_offshore_load_factor': energies_arr["wind_offshore"] / germany_installed_capacities["wind_offshore"],
    'solar_load_factor': energies_arr["solar"] / germany_installed_capacities["solar"],
    'gas_load_factor': energies_arr["gas"] / germany_installed_capacities["gas"],
}, index=[i for i in range(len(dates_de))])


germany_dataframe = germany_dataframe[germany_dataframe["price"].notna()]
germany_dataframe = germany_dataframe.dropna()


germany_dataframe.to_csv("germany.csv", encoding='utf-8', index=False)

germany_dataframe

,date,price,load,nuclear,wind_onshore,wind_offshore,solar,gas,nuclear_load_factor,wind_onshore_load_factor,wind_offshore_load_factor,solar_load_factor,gas_load_factor
0,01.01.2019 00:00 - 01.01.2019 01:00,28.32,43.52675,9.00150,19.99550,3.13650,0.0,3.27325,0.945933,0.377658,0.490615,0.0,0.103111
1,01.01.2019 01:00 - 01.01.2019 02:00,10.07,41.80050,8.53525,22.03650,2.86800,0.0,2.96725,0.896937,0.416207,0.448616,0.0,0.093471
2,01.01.2019 02:00 - 01.01.2019 03:00,-4.08,40.11250,7.95400,22.74825,2.45950,0.0,2.72025,0.835855,0.429650,0.384718,0.0,0.085691
3,01.01.2019 03:00 - 01.01.2019 04:00,-9.91,39.49025,7.22175,23.87025,2.69775,0.0,2.65325,0.758906,0.450841,0.421985,0.0,0.083580
4,01.01.2019 04:00 - 01.01.2019 05:00,-7.41,39.27150,7.12000,25.92150,2.57825,0.0,2.70600,0.748214,0.489584,0.403293,0.0,0.085242
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8756,31.12.2019 19:00 - 31.12.2019 20:00,46.00,51.34600,8.04500,8.45125,1.25100,0.0,5.84125,0.845418,0.159620,0.195683,0.0,0.184005
8757,31.12.2019 20:00 - 31.12.2019 21:00,42.20,48.34600,8.07600,8.00150,0.87300,0.0,5.68125,0.848676,0.151126,0.136556,0.0,0.178965
8758,31.12.2019 21:00 - 31.12.2019 22:00,39.74,46.62175,8.08050,6.94825,0.70375,0.0,5.53675,0.849149,0.131233,0.110081,0.0,0.174413
8759,31.12.2019 22:00 - 31.12.2019 23:00,38.88,46.15825,8.08000,6.70825,0.57475,0.0,5.44725,0.849096,0.126700,0.089903,0.0,0.171594
8760,31.12.2019 23:00 - 01.01.2020 00:00,37.39,44.31325,8.08875,6.07325,0.49975,0.0,5.34725,0.850016,0.114706,0.078171,0.0,0.168444

In [8]:
swedish_df = pd.read_csv("SE2.csv")

def func(x):
    return abs(float('.'.join(x.split(','))))

swedish_df['consumption'] = swedish_df['consumption'].apply(func)
swedish_df['price'] = swedish_df['price'].apply(func)

swedish_df['unspecified'] = swedish_df['unspecified'].apply(lambda x: x / 1000)
swedish_df['hydro'] = swedish_df['hydro'].apply(lambda x: x / 1000)
swedish_df['wind_onshore'] = swedish_df['wind_onshore'].apply(lambda x: x / 1000)
swedish_df['thermal'] = swedish_df['thermal'].apply(lambda x: x / 1000)
swedish_df['solar'] = swedish_df['solar'].apply(lambda x: x / 1000)
swedish_df['export/import'] = swedish_df['export/import'].apply(lambda x: x / 1000)



def define_load(row):
    return row["consumption"] + row["export/import"]

swedish_df["load"] = swedish_df.apply(lambda row: define_load(row), axis=1)


swedish_df.to_csv("sweden.csv", encoding='utf-8', index=False)

swedish_df

,consumption,price,unspecified,hydro,wind_onshore,thermal,solar,export/import,load
0,1.667,290.08,0.00003,1.339,1.406,0.199,0.000003,1.27730,2.94430
1,1.665,103.15,0.00002,1.202,1.256,0.192,0.000000,0.98520,2.65020
2,1.637,102.74,0.00002,1.115,1.085,0.190,0.000001,0.75259,2.38959
3,1.626,46.71,0.00002,1.170,0.943,0.188,0.000002,0.67513,2.30113
4,1.630,49.47,0.00000,1.207,0.859,0.186,0.000002,0.62112,2.25112
...,...,...,...,...,...,...,...,...,...
8755,1.792,338.15,0.00006,3.820,2.480,0.227,0.000014,4.73537,6.52737
8756,1.741,326.24,0.00015,3.313,2.435,0.210,0.000015,4.21704,5.95804
8757,1.719,327.29,0.00010,3.293,2.456,0.212,0.000016,4.24181,5.96081
8758,1.679,328.65,0.00013,3.127,2.263,0.216,0.000014,3.92645,5.60545
8759,1.650,322.07,0.00044,2.286,2.172,0.209,0.000014,3.01667,4.66667